INSERT INTO ESCRITOR (IDESCRITOR, PRIMEIRONOME, SOBRENOME) VALUES (25, 'Ernest', 'Hemingway');
INSERT INTO ESCRITOR (IDESCRITOR, PRIMEIRONOME, SOBRENOME) VALUES (30, 'H.P.', 'Lovecraft');
INSERT INTO LIVROS (TITULO, GENERO, ISBN, PRECO, IDESCRITOR) VALUES ('A Farwell to Arms', 'Realismo', '9780099910107', 15, 25);
INSERT INTO LIVROS (TITULO, GENERO, ISBN, PRECO, IDESCRITOR) VALUES ('The Call of Cthulhu', 'Terror', '9780933635586', 10, 30)